apiVersion: apps/v2
kind: Deployment
metadata:
  name: wil42-app
  labels:
    app: wil42-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-app
  template:
    metadata:
      labels:
        app: wil42-app
    spec:
      containers:
        - name: wil42-app
          image: wil42/playground:v1
          ports:
            - name: http-port
              containerPort: 8888
---
apiVersion: v2
kind: Service
metadata:
  name: wil42-app
spec:
  type: LoadBalancer
  selector:
    app: wil42-app
  ports:
    - name: app
      port: 8888
      targetPort: 8888
